# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

os: linux
dist: xenial

before_install:
  - openssl aes-256-cbc -K $encrypted_df44da40f911_key -iv $encrypted_df44da40f911_iv
    -in lab-devops-cloud-5aso-320323-626ff2619aab.json.enc -out ../lab-devops-cloud-5aso-320323-626ff2619aab.json
    -d

jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - python -m unittest -v test || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-5aso-lucas
        on:
          branch: main

    - stage: STG TEST
      script:
        - curl https://devopslab-5aso-lucas.herokuapp.com/ | grep Hello || travis_terminate 1;

    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../lab-devops-cloud-5aso-320323-626ff2619aab.json
        project: lab-devops-cloud-5aso-320323
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://lab-devops-cloud-5aso-320323.uc.r.appspot.com/ | grep Hello || travis_terminate 1;

addons:
  sonarcloud:
    organization: lucashenriquedesouza
    token: ${SONAR_TOKEN}
